package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "CALCULATION_TEST".
 */
public class CalculationTest implements Parcelable{

    private Long id;
    /** Not-null value. */
    private String itemNo;
    private String stem;
    private Boolean hasStemPic;
    private String picName;
    private Boolean hasStemSound;
    private String soundName;
    private String choiceA;
    private String choiceB;
    private String choiceC;
    private String choiceD;
    private String rightAnswer;

    public CalculationTest() {
    }

    public CalculationTest(Long id) {
        this.id = id;
    }

    public CalculationTest(Long id, String itemNo, String stem, Boolean hasStemPic, String picName, Boolean hasStemSound, String soundName, String choiceA, String choiceB, String choiceC, String choiceD, String rightAnswer) {
        this.id = id;
        this.itemNo = itemNo;
        this.stem = stem;
        this.hasStemPic = hasStemPic;
        this.picName = picName;
        this.hasStemSound = hasStemSound;
        this.soundName = soundName;
        this.choiceA = choiceA;
        this.choiceB = choiceB;
        this.choiceC = choiceC;
        this.choiceD = choiceD;
        this.rightAnswer = rightAnswer;
    }

    protected CalculationTest(Parcel in) {
        itemNo = in.readString();
        stem = in.readString();
        picName = in.readString();
        soundName = in.readString();
        choiceA = in.readString();
        choiceB = in.readString();
        choiceC = in.readString();
        choiceD = in.readString();
        rightAnswer = in.readString();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(itemNo);
        dest.writeString(stem);
        dest.writeString(picName);
        dest.writeString(soundName);
        dest.writeString(choiceA);
        dest.writeString(choiceB);
        dest.writeString(choiceC);
        dest.writeString(choiceD);
        dest.writeString(rightAnswer);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<CalculationTest> CREATOR = new Creator<CalculationTest>() {
        @Override
        public CalculationTest createFromParcel(Parcel in) {
            return new CalculationTest(in);
        }

        @Override
        public CalculationTest[] newArray(int size) {
            return new CalculationTest[size];
        }
    };

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getItemNo() {
        return itemNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    public String getStem() {
        return stem;
    }

    public void setStem(String stem) {
        this.stem = stem;
    }

    public Boolean getHasStemPic() {
        return hasStemPic;
    }

    public void setHasStemPic(Boolean hasStemPic) {
        this.hasStemPic = hasStemPic;
    }

    public String getPicName() {
        return picName;
    }

    public void setPicName(String picName) {
        this.picName = picName;
    }

    public Boolean getHasStemSound() {
        return hasStemSound;
    }

    public void setHasStemSound(Boolean hasStemSound) {
        this.hasStemSound = hasStemSound;
    }

    public String getSoundName() {
        return soundName;
    }

    public void setSoundName(String soundName) {
        this.soundName = soundName;
    }

    public String getChoiceA() {
        return choiceA;
    }

    public void setChoiceA(String choiceA) {
        this.choiceA = choiceA;
    }

    public String getChoiceB() {
        return choiceB;
    }

    public void setChoiceB(String choiceB) {
        this.choiceB = choiceB;
    }

    public String getChoiceC() {
        return choiceC;
    }

    public void setChoiceC(String choiceC) {
        this.choiceC = choiceC;
    }

    public String getChoiceD() {
        return choiceD;
    }

    public void setChoiceD(String choiceD) {
        this.choiceD = choiceD;
    }

    public String getRightAnswer() {
        return rightAnswer;
    }

    public void setRightAnswer(String rightAnswer) {
        this.rightAnswer = rightAnswer;
    }

}
