package com.neusoft.sample.GreenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.neusoft.sample.GreenDao.User;
import com.neusoft.sample.GreenDao.TextOneStructure;
import com.neusoft.sample.GreenDao.TextTwoStructure;
import com.neusoft.sample.GreenDao.StudyGoodTerm;
import com.neusoft.sample.GreenDao.StudyGoodInfo;
import com.neusoft.sample.GreenDao.StudyGoodItem;
import com.neusoft.sample.GreenDao.CalculationTest;
import com.neusoft.sample.GreenDao.XTCSGJ;
import com.neusoft.sample.GreenDao.XTCSJG;
import com.neusoft.sample.GreenDao.XTCTJL;
import com.neusoft.sample.GreenDao.XTDCTM;
import com.neusoft.sample.GreenDao.UserDoSubjectInfo;
import com.neusoft.sample.GreenDao.Ranklist;
import com.neusoft.sample.GreenDao.ErrorSubjectNub;
import com.neusoft.sample.GreenDao.Notification;
import com.neusoft.sample.GreenDao.teacher;

import com.neusoft.sample.GreenDao.UserDao;
import com.neusoft.sample.GreenDao.TextOneStructureDao;
import com.neusoft.sample.GreenDao.TextTwoStructureDao;
import com.neusoft.sample.GreenDao.StudyGoodTermDao;
import com.neusoft.sample.GreenDao.StudyGoodInfoDao;
import com.neusoft.sample.GreenDao.StudyGoodItemDao;
import com.neusoft.sample.GreenDao.CalculationTestDao;
import com.neusoft.sample.GreenDao.XTCSGJDao;
import com.neusoft.sample.GreenDao.XTCSJGDao;
import com.neusoft.sample.GreenDao.XTCTJLDao;
import com.neusoft.sample.GreenDao.XTDCTMDao;
import com.neusoft.sample.GreenDao.UserDoSubjectInfoDao;
import com.neusoft.sample.GreenDao.RanklistDao;
import com.neusoft.sample.GreenDao.ErrorSubjectNubDao;
import com.neusoft.sample.GreenDao.NotificationDao;
import com.neusoft.sample.GreenDao.teacherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig textOneStructureDaoConfig;
    private final DaoConfig textTwoStructureDaoConfig;
    private final DaoConfig studyGoodTermDaoConfig;
    private final DaoConfig studyGoodInfoDaoConfig;
    private final DaoConfig studyGoodItemDaoConfig;
    private final DaoConfig calculationTestDaoConfig;
    private final DaoConfig xTCSGJDaoConfig;
    private final DaoConfig xTCSJGDaoConfig;
    private final DaoConfig xTCTJLDaoConfig;
    private final DaoConfig xTDCTMDaoConfig;
    private final DaoConfig userDoSubjectInfoDaoConfig;
    private final DaoConfig ranklistDaoConfig;
    private final DaoConfig errorSubjectNubDaoConfig;
    private final DaoConfig notificationDaoConfig;
    private final DaoConfig teacherDaoConfig;

    private final UserDao userDao;
    private final TextOneStructureDao textOneStructureDao;
    private final TextTwoStructureDao textTwoStructureDao;
    private final StudyGoodTermDao studyGoodTermDao;
    private final StudyGoodInfoDao studyGoodInfoDao;
    private final StudyGoodItemDao studyGoodItemDao;
    private final CalculationTestDao calculationTestDao;
    private final XTCSGJDao xTCSGJDao;
    private final XTCSJGDao xTCSJGDao;
    private final XTCTJLDao xTCTJLDao;
    private final XTDCTMDao xTDCTMDao;
    private final UserDoSubjectInfoDao userDoSubjectInfoDao;
    private final RanklistDao ranklistDao;
    private final ErrorSubjectNubDao errorSubjectNubDao;
    private final NotificationDao notificationDao;
    private final teacherDao teacherDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        textOneStructureDaoConfig = daoConfigMap.get(TextOneStructureDao.class).clone();
        textOneStructureDaoConfig.initIdentityScope(type);

        textTwoStructureDaoConfig = daoConfigMap.get(TextTwoStructureDao.class).clone();
        textTwoStructureDaoConfig.initIdentityScope(type);

        studyGoodTermDaoConfig = daoConfigMap.get(StudyGoodTermDao.class).clone();
        studyGoodTermDaoConfig.initIdentityScope(type);

        studyGoodInfoDaoConfig = daoConfigMap.get(StudyGoodInfoDao.class).clone();
        studyGoodInfoDaoConfig.initIdentityScope(type);

        studyGoodItemDaoConfig = daoConfigMap.get(StudyGoodItemDao.class).clone();
        studyGoodItemDaoConfig.initIdentityScope(type);

        calculationTestDaoConfig = daoConfigMap.get(CalculationTestDao.class).clone();
        calculationTestDaoConfig.initIdentityScope(type);

        xTCSGJDaoConfig = daoConfigMap.get(XTCSGJDao.class).clone();
        xTCSGJDaoConfig.initIdentityScope(type);

        xTCSJGDaoConfig = daoConfigMap.get(XTCSJGDao.class).clone();
        xTCSJGDaoConfig.initIdentityScope(type);

        xTCTJLDaoConfig = daoConfigMap.get(XTCTJLDao.class).clone();
        xTCTJLDaoConfig.initIdentityScope(type);

        xTDCTMDaoConfig = daoConfigMap.get(XTDCTMDao.class).clone();
        xTDCTMDaoConfig.initIdentityScope(type);

        userDoSubjectInfoDaoConfig = daoConfigMap.get(UserDoSubjectInfoDao.class).clone();
        userDoSubjectInfoDaoConfig.initIdentityScope(type);

        ranklistDaoConfig = daoConfigMap.get(RanklistDao.class).clone();
        ranklistDaoConfig.initIdentityScope(type);

        errorSubjectNubDaoConfig = daoConfigMap.get(ErrorSubjectNubDao.class).clone();
        errorSubjectNubDaoConfig.initIdentityScope(type);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(teacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        textOneStructureDao = new TextOneStructureDao(textOneStructureDaoConfig, this);
        textTwoStructureDao = new TextTwoStructureDao(textTwoStructureDaoConfig, this);
        studyGoodTermDao = new StudyGoodTermDao(studyGoodTermDaoConfig, this);
        studyGoodInfoDao = new StudyGoodInfoDao(studyGoodInfoDaoConfig, this);
        studyGoodItemDao = new StudyGoodItemDao(studyGoodItemDaoConfig, this);
        calculationTestDao = new CalculationTestDao(calculationTestDaoConfig, this);
        xTCSGJDao = new XTCSGJDao(xTCSGJDaoConfig, this);
        xTCSJGDao = new XTCSJGDao(xTCSJGDaoConfig, this);
        xTCTJLDao = new XTCTJLDao(xTCTJLDaoConfig, this);
        xTDCTMDao = new XTDCTMDao(xTDCTMDaoConfig, this);
        userDoSubjectInfoDao = new UserDoSubjectInfoDao(userDoSubjectInfoDaoConfig, this);
        ranklistDao = new RanklistDao(ranklistDaoConfig, this);
        errorSubjectNubDao = new ErrorSubjectNubDao(errorSubjectNubDaoConfig, this);
        notificationDao = new NotificationDao(notificationDaoConfig, this);
        teacherDao = new teacherDao(teacherDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(TextOneStructure.class, textOneStructureDao);
        registerDao(TextTwoStructure.class, textTwoStructureDao);
        registerDao(StudyGoodTerm.class, studyGoodTermDao);
        registerDao(StudyGoodInfo.class, studyGoodInfoDao);
        registerDao(StudyGoodItem.class, studyGoodItemDao);
        registerDao(CalculationTest.class, calculationTestDao);
        registerDao(XTCSGJ.class, xTCSGJDao);
        registerDao(XTCSJG.class, xTCSJGDao);
        registerDao(XTCTJL.class, xTCTJLDao);
        registerDao(XTDCTM.class, xTDCTMDao);
        registerDao(UserDoSubjectInfo.class, userDoSubjectInfoDao);
        registerDao(Ranklist.class, ranklistDao);
        registerDao(ErrorSubjectNub.class, errorSubjectNubDao);
        registerDao(Notification.class, notificationDao);
        registerDao(teacher.class, teacherDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        textOneStructureDaoConfig.getIdentityScope().clear();
        textTwoStructureDaoConfig.getIdentityScope().clear();
        studyGoodTermDaoConfig.getIdentityScope().clear();
        studyGoodInfoDaoConfig.getIdentityScope().clear();
        studyGoodItemDaoConfig.getIdentityScope().clear();
        calculationTestDaoConfig.getIdentityScope().clear();
        xTCSGJDaoConfig.getIdentityScope().clear();
        xTCSJGDaoConfig.getIdentityScope().clear();
        xTCTJLDaoConfig.getIdentityScope().clear();
        xTDCTMDaoConfig.getIdentityScope().clear();
        userDoSubjectInfoDaoConfig.getIdentityScope().clear();
        ranklistDaoConfig.getIdentityScope().clear();
        errorSubjectNubDaoConfig.getIdentityScope().clear();
        notificationDaoConfig.getIdentityScope().clear();
        teacherDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TextOneStructureDao getTextOneStructureDao() {
        return textOneStructureDao;
    }

    public TextTwoStructureDao getTextTwoStructureDao() {
        return textTwoStructureDao;
    }

    public StudyGoodTermDao getStudyGoodTermDao() {
        return studyGoodTermDao;
    }

    public StudyGoodInfoDao getStudyGoodInfoDao() {
        return studyGoodInfoDao;
    }

    public StudyGoodItemDao getStudyGoodItemDao() {
        return studyGoodItemDao;
    }

    public CalculationTestDao getCalculationTestDao() {
        return calculationTestDao;
    }

    public XTCSGJDao getXTCSGJDao() {
        return xTCSGJDao;
    }

    public XTCSJGDao getXTCSJGDao() {
        return xTCSJGDao;
    }

    public XTCTJLDao getXTCTJLDao() {
        return xTCTJLDao;
    }

    public XTDCTMDao getXTDCTMDao() {
        return xTDCTMDao;
    }

    public UserDoSubjectInfoDao getUserDoSubjectInfoDao() {
        return userDoSubjectInfoDao;
    }

    public RanklistDao getRanklistDao() {
        return ranklistDao;
    }

    public ErrorSubjectNubDao getErrorSubjectNubDao() {
        return errorSubjectNubDao;
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

    public teacherDao getTeacherDao() {
        return teacherDao;
    }

}
