package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ERROR_SUBJECT_NUB".
 */
public class ErrorSubjectNub {

    private Long id;
    private String xtdctm_id;
    private String examination_number;
    private Integer ismastered;
    private String test_group_number;
    private String user_id;
    private Integer xtcsjl_id;
    private String answer;
    private String jl_datetime;
    private String tableName;

    public ErrorSubjectNub() {
    }

    public ErrorSubjectNub(Long id) {
        this.id = id;
    }

    public ErrorSubjectNub(Long id, String xtdctm_id, String examination_number, Integer ismastered, String test_group_number, String user_id, Integer xtcsjl_id, String answer, String jl_datetime, String tableName) {
        this.id = id;
        this.xtdctm_id = xtdctm_id;
        this.examination_number = examination_number;
        this.ismastered = ismastered;
        this.test_group_number = test_group_number;
        this.user_id = user_id;
        this.xtcsjl_id = xtcsjl_id;
        this.answer = answer;
        this.jl_datetime = jl_datetime;
        this.tableName = tableName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getXtdctm_id() {
        return xtdctm_id;
    }

    public void setXtdctm_id(String xtdctm_id) {
        this.xtdctm_id = xtdctm_id;
    }

    public String getExamination_number() {
        return examination_number;
    }

    public void setExamination_number(String examination_number) {
        this.examination_number = examination_number;
    }

    public Integer getIsmastered() {
        return ismastered;
    }

    public void setIsmastered(Integer ismastered) {
        this.ismastered = ismastered;
    }

    public String getTest_group_number() {
        return test_group_number;
    }

    public void setTest_group_number(String test_group_number) {
        this.test_group_number = test_group_number;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public Integer getXtcsjl_id() {
        return xtcsjl_id;
    }

    public void setXtcsjl_id(Integer xtcsjl_id) {
        this.xtcsjl_id = xtcsjl_id;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getJl_datetime() {
        return jl_datetime;
    }

    public void setJl_datetime(String jl_datetime) {
        this.jl_datetime = jl_datetime;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

}
