package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTIFICATION".
 */
public class Notification implements Comparable<Notification>{

    private Long id;
    /** Not-null value. */
    private String notification_id;
    private String titleNo;
    private String title;
    private String content;
    private String notify_publisher;
    private java.util.Date notify_time;
    private String notify_check_id;
    private String is_read;
    /** Not-null value. */
    private String unique_id;

    public Notification() {
    }

    public Notification(Long id) {
        this.id = id;
    }

    public Notification(Long id, String notification_id, String titleNo, String title, String content, String notify_publisher, java.util.Date notify_time, String notify_check_id, String is_read, String unique_id) {
        this.id = id;
        this.notification_id = notification_id;
        this.titleNo = titleNo;
        this.title = title;
        this.content = content;
        this.notify_publisher = notify_publisher;
        this.notify_time = notify_time;
        this.notify_check_id = notify_check_id;
        this.is_read = is_read;
        this.unique_id = unique_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNotification_id() {
        return notification_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNotification_id(String notification_id) {
        this.notification_id = notification_id;
    }

    public String getTitleNo() {
        return titleNo;
    }

    public void setTitleNo(String titleNo) {
        this.titleNo = titleNo;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getNotify_publisher() {
        return notify_publisher;
    }

    public void setNotify_publisher(String notify_publisher) {
        this.notify_publisher = notify_publisher;
    }

    public java.util.Date getNotify_time() {
        return notify_time;
    }

    public void setNotify_time(java.util.Date notify_time) {
        this.notify_time = notify_time;
    }

    public String getNotify_check_id() {
        return notify_check_id;
    }

    public void setNotify_check_id(String notify_check_id) {
        this.notify_check_id = notify_check_id;
    }

    public String getIs_read() {
        return is_read;
    }

    public void setIs_read(String is_read) {
        this.is_read = is_read;
    }

    /** Not-null value. */
    public String getUnique_id() {
        return unique_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUnique_id(String unique_id) {
        this.unique_id = unique_id;
    }

    @Override
    public int compareTo(Notification another) {
        //notify_time.
        if (notify_time.getDate() > another.notify_time.getDate()) return -1;
        else if (notify_time.getDate() == another.notify_time.getDate()) return 0;
        else return 1;
    }

}
