package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "RANKLIST".
 */
public class Ranklist implements Comparable<Ranklist> {

    private Long id;
    private String unique_id;
    private String integral_id;
    private String user_id;
    private Integer integral_number;
    private String month;
    private String text;
    private String real_name;
    private String email;
    private String class_number;
    private String mobile;
    private String password;
    private String role;
    private java.util.Date indate;
    private String user_icon_url;
    private String gender;
    private String qq_number;
    private String weixin_number;
    private String motto;
    private String recipient;
    private String address;
    private String phone;
    private String schoolName;

    public Ranklist() {
    }

    public Ranklist(Long id) {
        this.id = id;
    }

    public Ranklist(Long id, String unique_id, String integral_id, String user_id, Integer integral_number, String month, String text, String real_name, String email, String class_number, String mobile, String password, String role, java.util.Date indate, String user_icon_url, String gender, String qq_number, String weixin_number, String motto, String recipient, String address, String phone, String schoolName) {
        this.id = id;
        this.unique_id = unique_id;
        this.integral_id = integral_id;
        this.user_id = user_id;
        this.integral_number = integral_number;
        this.month = month;
        this.text = text;
        this.real_name = real_name;
        this.email = email;
        this.class_number = class_number;
        this.mobile = mobile;
        this.password = password;
        this.role = role;
        this.indate = indate;
        this.user_icon_url = user_icon_url;
        this.gender = gender;
        this.qq_number = qq_number;
        this.weixin_number = weixin_number;
        this.motto = motto;
        this.recipient = recipient;
        this.address = address;
        this.phone = phone;
        this.schoolName = schoolName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUnique_id() {
        return unique_id;
    }

    public void setUnique_id(String unique_id) {
        this.unique_id = unique_id;
    }

    public String getIntegral_id() {
        return integral_id;
    }

    public void setIntegral_id(String integral_id) {
        this.integral_id = integral_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public Integer getIntegral_number() {
        return integral_number;
    }

    public void setIntegral_number(Integer integral_number) {
        this.integral_number = integral_number;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getReal_name() {
        return real_name;
    }

    public void setReal_name(String real_name) {
        this.real_name = real_name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getClass_number() {
        return class_number;
    }

    public void setClass_number(String class_number) {
        this.class_number = class_number;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public java.util.Date getIndate() {
        return indate;
    }

    public void setIndate(java.util.Date indate) {
        this.indate = indate;
    }

    public String getUser_icon_url() {
        return user_icon_url;
    }

    public void setUser_icon_url(String user_icon_url) {
        this.user_icon_url = user_icon_url;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getQq_number() {
        return qq_number;
    }

    public void setQq_number(String qq_number) {
        this.qq_number = qq_number;
    }

    public String getWeixin_number() {
        return weixin_number;
    }

    public void setWeixin_number(String weixin_number) {
        this.weixin_number = weixin_number;
    }

    public String getMotto() {
        return motto;
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }

    public String getRecipient() {
        return recipient;
    }

    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    @Override
    public int compareTo(Ranklist another) {
        if (integral_number.intValue() > another.integral_number.intValue()) return -1;
        else if (integral_number.intValue() == another.integral_number.intValue()) return 0;
        else return 1;
    }
}
