package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDY_GOOD_INFO".
 */
public class StudyGoodInfo {

    private Long id;
    /** Not-null value. */
    private String productNo;
    private String bookGroupNo;
    private String introduce;
    private String price;
    private String overdue;
    private String priceOnSale;
    private String dueDate;

    public StudyGoodInfo() {
    }

    public StudyGoodInfo(Long id) {
        this.id = id;
    }

    public StudyGoodInfo(Long id, String productNo, String bookGroupNo, String introduce, String price, String overdue, String priceOnSale, String dueDate) {
        this.id = id;
        this.productNo = productNo;
        this.bookGroupNo = bookGroupNo;
        this.introduce = introduce;
        this.price = price;
        this.overdue = overdue;
        this.priceOnSale = priceOnSale;
        this.dueDate = dueDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getProductNo() {
        return productNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    public String getBookGroupNo() {
        return bookGroupNo;
    }

    public void setBookGroupNo(String bookGroupNo) {
        this.bookGroupNo = bookGroupNo;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getOverdue() {
        return overdue;
    }

    public void setOverdue(String overdue) {
        this.overdue = overdue;
    }

    public String getPriceOnSale() {
        return priceOnSale;
    }

    public void setPriceOnSale(String priceOnSale) {
        this.priceOnSale = priceOnSale;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

}
