package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDY_GOOD_ITEM".
 */
public class StudyGoodItem {

    private Long id;
    /** Not-null value. */
    private String productItemNo;
    private String bookNo;
    private String name;
    private String productId;

    public StudyGoodItem() {
    }

    public StudyGoodItem(Long id) {
        this.id = id;
    }

    public StudyGoodItem(Long id, String productItemNo, String bookNo, String name, String productId) {
        this.id = id;
        this.productItemNo = productItemNo;
        this.bookNo = bookNo;
        this.name = name;
        this.productId = productId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getProductItemNo() {
        return productItemNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProductItemNo(String productItemNo) {
        this.productItemNo = productItemNo;
    }

    public String getBookNo() {
        return bookNo;
    }

    public void setBookNo(String bookNo) {
        this.bookNo = bookNo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

}
