package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDY_GOOD_TERM".
 */
public class StudyGoodTerm {

    private Long id;
    /** Not-null value. */
    private String bookNo;
    private String name;
    private String grade;
    private Integer term;
    private Integer type;
    private Boolean hasIntroducePDF;
    private Integer chapterNum;
    private String version;
    private Integer hasCoverPIC;
    private java.util.Date updateTime;

    public StudyGoodTerm() {
    }

    public StudyGoodTerm(Long id) {
        this.id = id;
    }

    public StudyGoodTerm(Long id, String bookNo, String name, String grade, Integer term, Integer type, Boolean hasIntroducePDF, Integer chapterNum, String version, Integer hasCoverPIC, java.util.Date updateTime) {
        this.id = id;
        this.bookNo = bookNo;
        this.name = name;
        this.grade = grade;
        this.term = term;
        this.type = type;
        this.hasIntroducePDF = hasIntroducePDF;
        this.chapterNum = chapterNum;
        this.version = version;
        this.hasCoverPIC = hasCoverPIC;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookNo() {
        return bookNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookNo(String bookNo) {
        this.bookNo = bookNo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public Integer getTerm() {
        return term;
    }

    public void setTerm(Integer term) {
        this.term = term;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Boolean getHasIntroducePDF() {
        return hasIntroducePDF;
    }

    public void setHasIntroducePDF(Boolean hasIntroducePDF) {
        this.hasIntroducePDF = hasIntroducePDF;
    }

    public Integer getChapterNum() {
        return chapterNum;
    }

    public void setChapterNum(Integer chapterNum) {
        this.chapterNum = chapterNum;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getHasCoverPIC() {
        return hasCoverPIC;
    }

    public void setHasCoverPIC(Integer hasCoverPIC) {
        this.hasCoverPIC = hasCoverPIC;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "StudyGoodTerm{" +
                "id=" + id +
                ", bookNo='" + bookNo + '\'' +
                ", name='" + name + '\'' +
                ", grade='" + grade + '\'' +
                ", term=" + term +
                ", type=" + type +
                ", hasIntroducePDF=" + hasIntroducePDF +
                ", chapterNum=" + chapterNum +
                ", version='" + version + '\'' +
                ", hasCoverPIC=" + hasCoverPIC +
                ", updateTime=" + updateTime +
                '}';
    }

}
