package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEACHER".
 */
public class teacher {

    private Long id;
    /** Not-null value. */
    private String teacherName;
    private String realName;
    private String nickName;
    private String sex;
    private String birthday;
    private String motto;
    private String teacher_icon_url;
    private String password;
    private String totalIntegral;
    private String userIntegral;
    private String homeWorkIntegral;
    private String articleIntegral;
    private String feedbackIntegral;
    private String schoolNum;
    private String schoolName;
    private String isClassTeacher;
    private String subjectNum;
    private String subjectName;
    private String textBookNum;
    private String textBookName;
    private String classNum1;
    private String className1;
    private String peopleNum1;
    private String peopleRegister1;
    private String peopleBuy1;
    private String classNum2;
    private String className2;
    private String peopleNum2;
    private String peopleRegister2;
    private String peopleBuy2;
    private String classNum3;
    private String className3;
    private String peopleNum3;
    private String peopleRegister3;
    private String peopleBuy3;
    private String classNum4;
    private String className4;
    private String peopleNum4;
    private String peopleRegister4;
    private String peopleBuy4;
    private String qqNum;
    private String weChatNum;
    private String email;

    public teacher() {
    }

    public teacher(Long id) {
        this.id = id;
    }

    public teacher(Long id, String teacherName, String realName, String nickName, String sex, String birthday, String motto, String teacher_icon_url, String password, String totalIntegral, String userIntegral, String homeWorkIntegral, String articleIntegral, String feedbackIntegral, String schoolNum, String schoolName, String isClassTeacher, String subjectNum, String subjectName, String textBookNum, String textBookName, String classNum1, String className1, String peopleNum1, String peopleRegister1, String peopleBuy1, String classNum2, String className2, String peopleNum2, String peopleRegister2, String peopleBuy2, String classNum3, String className3, String peopleNum3, String peopleRegister3, String peopleBuy3, String classNum4, String className4, String peopleNum4, String peopleRegister4, String peopleBuy4, String qqNum, String weChatNum, String email) {
        this.id = id;
        this.teacherName = teacherName;
        this.realName = realName;
        this.nickName = nickName;
        this.sex = sex;
        this.birthday = birthday;
        this.motto = motto;
        this.teacher_icon_url = teacher_icon_url;
        this.password = password;
        this.totalIntegral = totalIntegral;
        this.userIntegral = userIntegral;
        this.homeWorkIntegral = homeWorkIntegral;
        this.articleIntegral = articleIntegral;
        this.feedbackIntegral = feedbackIntegral;
        this.schoolNum = schoolNum;
        this.schoolName = schoolName;
        this.isClassTeacher = isClassTeacher;
        this.subjectNum = subjectNum;
        this.subjectName = subjectName;
        this.textBookNum = textBookNum;
        this.textBookName = textBookName;
        this.classNum1 = classNum1;
        this.className1 = className1;
        this.peopleNum1 = peopleNum1;
        this.peopleRegister1 = peopleRegister1;
        this.peopleBuy1 = peopleBuy1;
        this.classNum2 = classNum2;
        this.className2 = className2;
        this.peopleNum2 = peopleNum2;
        this.peopleRegister2 = peopleRegister2;
        this.peopleBuy2 = peopleBuy2;
        this.classNum3 = classNum3;
        this.className3 = className3;
        this.peopleNum3 = peopleNum3;
        this.peopleRegister3 = peopleRegister3;
        this.peopleBuy3 = peopleBuy3;
        this.classNum4 = classNum4;
        this.className4 = className4;
        this.peopleNum4 = peopleNum4;
        this.peopleRegister4 = peopleRegister4;
        this.peopleBuy4 = peopleBuy4;
        this.qqNum = qqNum;
        this.weChatNum = weChatNum;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTeacherName() {
        return teacherName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getMotto() {
        return motto;
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }

    public String getTeacher_icon_url() {
        return teacher_icon_url;
    }

    public void setTeacher_icon_url(String teacher_icon_url) {
        this.teacher_icon_url = teacher_icon_url;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getTotalIntegral() {
        return totalIntegral;
    }

    public void setTotalIntegral(String totalIntegral) {
        this.totalIntegral = totalIntegral;
    }

    public String getUserIntegral() {
        return userIntegral;
    }

    public void setUserIntegral(String userIntegral) {
        this.userIntegral = userIntegral;
    }

    public String getHomeWorkIntegral() {
        return homeWorkIntegral;
    }

    public void setHomeWorkIntegral(String homeWorkIntegral) {
        this.homeWorkIntegral = homeWorkIntegral;
    }

    public String getArticleIntegral() {
        return articleIntegral;
    }

    public void setArticleIntegral(String articleIntegral) {
        this.articleIntegral = articleIntegral;
    }

    public String getFeedbackIntegral() {
        return feedbackIntegral;
    }

    public void setFeedbackIntegral(String feedbackIntegral) {
        this.feedbackIntegral = feedbackIntegral;
    }

    public String getSchoolNum() {
        return schoolNum;
    }

    public void setSchoolNum(String schoolNum) {
        this.schoolNum = schoolNum;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    public String getIsClassTeacher() {
        return isClassTeacher;
    }

    public void setIsClassTeacher(String isClassTeacher) {
        this.isClassTeacher = isClassTeacher;
    }

    public String getSubjectNum() {
        return subjectNum;
    }

    public void setSubjectNum(String subjectNum) {
        this.subjectNum = subjectNum;
    }

    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    public String getTextBookNum() {
        return textBookNum;
    }

    public void setTextBookNum(String textBookNum) {
        this.textBookNum = textBookNum;
    }

    public String getTextBookName() {
        return textBookName;
    }

    public void setTextBookName(String textBookName) {
        this.textBookName = textBookName;
    }

    public String getClassNum1() {
        return classNum1;
    }

    public void setClassNum1(String classNum1) {
        this.classNum1 = classNum1;
    }

    public String getClassName1() {
        return className1;
    }

    public void setClassName1(String className1) {
        this.className1 = className1;
    }

    public String getPeopleNum1() {
        return peopleNum1;
    }

    public void setPeopleNum1(String peopleNum1) {
        this.peopleNum1 = peopleNum1;
    }

    public String getPeopleRegister1() {
        return peopleRegister1;
    }

    public void setPeopleRegister1(String peopleRegister1) {
        this.peopleRegister1 = peopleRegister1;
    }

    public String getPeopleBuy1() {
        return peopleBuy1;
    }

    public void setPeopleBuy1(String peopleBuy1) {
        this.peopleBuy1 = peopleBuy1;
    }

    public String getClassNum2() {
        return classNum2;
    }

    public void setClassNum2(String classNum2) {
        this.classNum2 = classNum2;
    }

    public String getClassName2() {
        return className2;
    }

    public void setClassName2(String className2) {
        this.className2 = className2;
    }

    public String getPeopleNum2() {
        return peopleNum2;
    }

    public void setPeopleNum2(String peopleNum2) {
        this.peopleNum2 = peopleNum2;
    }

    public String getPeopleRegister2() {
        return peopleRegister2;
    }

    public void setPeopleRegister2(String peopleRegister2) {
        this.peopleRegister2 = peopleRegister2;
    }

    public String getPeopleBuy2() {
        return peopleBuy2;
    }

    public void setPeopleBuy2(String peopleBuy2) {
        this.peopleBuy2 = peopleBuy2;
    }

    public String getClassNum3() {
        return classNum3;
    }

    public void setClassNum3(String classNum3) {
        this.classNum3 = classNum3;
    }

    public String getClassName3() {
        return className3;
    }

    public void setClassName3(String className3) {
        this.className3 = className3;
    }

    public String getPeopleNum3() {
        return peopleNum3;
    }

    public void setPeopleNum3(String peopleNum3) {
        this.peopleNum3 = peopleNum3;
    }

    public String getPeopleRegister3() {
        return peopleRegister3;
    }

    public void setPeopleRegister3(String peopleRegister3) {
        this.peopleRegister3 = peopleRegister3;
    }

    public String getPeopleBuy3() {
        return peopleBuy3;
    }

    public void setPeopleBuy3(String peopleBuy3) {
        this.peopleBuy3 = peopleBuy3;
    }

    public String getClassNum4() {
        return classNum4;
    }

    public void setClassNum4(String classNum4) {
        this.classNum4 = classNum4;
    }

    public String getClassName4() {
        return className4;
    }

    public void setClassName4(String className4) {
        this.className4 = className4;
    }

    public String getPeopleNum4() {
        return peopleNum4;
    }

    public void setPeopleNum4(String peopleNum4) {
        this.peopleNum4 = peopleNum4;
    }

    public String getPeopleRegister4() {
        return peopleRegister4;
    }

    public void setPeopleRegister4(String peopleRegister4) {
        this.peopleRegister4 = peopleRegister4;
    }

    public String getPeopleBuy4() {
        return peopleBuy4;
    }

    public void setPeopleBuy4(String peopleBuy4) {
        this.peopleBuy4 = peopleBuy4;
    }

    public String getQqNum() {
        return qqNum;
    }

    public void setQqNum(String qqNum) {
        this.qqNum = qqNum;
    }

    public String getWeChatNum() {
        return weChatNum;
    }

    public void setWeChatNum(String weChatNum) {
        this.weChatNum = weChatNum;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
