package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.Date;

/**
 * Entity mapped to table "USER_DO_SUBJECT_INFO".
 */
public class UserDoSubjectInfo {

    private Long id;
    private String test_group_number;
    private String user_id;
    private Integer time;
    private Date testtime;
    private String xtdctm_id;
    private String examination_number;
    private Integer ismastered;
    private Integer xtcsjg_id;
    private Integer score;
    private Integer number_error;
    private Integer number_success;
    private Integer duration;
    private Date jg_datetime;
    private Integer xtcsjl_id;
    private String answer;
    private Date jl_datetime;
    private String tableName;

    public UserDoSubjectInfo() {
    }

    public UserDoSubjectInfo(Long id) {
        this.id = id;
    }

    public UserDoSubjectInfo(Long id, String test_group_number, String user_id, Integer time, Date testtime, String xtdctm_id, String examination_number, Integer ismastered, Integer xtcsjg_id, Integer score, Integer number_error, Integer number_success, Integer duration, Date jg_datetime, Integer xtcsjl_id, String answer, Date jl_datetime, String tableName) {
        this.id = id;
        this.test_group_number = test_group_number;
        this.user_id = user_id;
        this.time = time;
        this.testtime = testtime;
        this.xtdctm_id = xtdctm_id;
        this.examination_number = examination_number;
        this.ismastered = ismastered;
        this.xtcsjg_id = xtcsjg_id;
        this.score = score;
        this.number_error = number_error;
        this.number_success = number_success;
        this.duration = duration;
        this.jg_datetime = jg_datetime;
        this.xtcsjl_id = xtcsjl_id;
        this.answer = answer;
        this.jl_datetime = jl_datetime;
        this.tableName = tableName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTest_group_number() {
        return test_group_number;
    }

    public void setTest_group_number(String test_group_number) {
        this.test_group_number = test_group_number;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public Integer getTime() {
        return time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    public Date getTesttime() {
        return testtime;
    }

    public void setTesttime(Date testtime) {
        this.testtime = testtime;
    }

    public String getXtdctm_id() {
        return xtdctm_id;
    }

    public void setXtdctm_id(String xtdctm_id) {
        this.xtdctm_id = xtdctm_id;
    }

    public String getExamination_number() {
        return examination_number;
    }

    public void setExamination_number(String examination_number) {
        this.examination_number = examination_number;
    }

    public Integer getIsmastered() {
        return ismastered;
    }

    public void setIsmastered(Integer ismastered) {
        this.ismastered = ismastered;
    }

    public Integer getXtcsjg_id() {
        return xtcsjg_id;
    }

    public void setXtcsjg_id(Integer xtcsjg_id) {
        this.xtcsjg_id = xtcsjg_id;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getNumber_error() {
        return number_error;
    }

    public void setNumber_error(Integer number_error) {
        this.number_error = number_error;
    }

    public Integer getNumber_success() {
        return number_success;
    }

    public void setNumber_success(Integer number_success) {
        this.number_success = number_success;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Date getJg_datetime() {
        return jg_datetime;
    }

    public void setJg_datetime(Date jg_datetime) {
        this.jg_datetime = jg_datetime;
    }

    public Integer getXtcsjl_id() {
        return xtcsjl_id;
    }

    public void setXtcsjl_id(Integer xtcsjl_id) {
        this.xtcsjl_id = xtcsjl_id;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Date getJl_datetime() {
        return jl_datetime;
    }

    public void setJl_datetime(Date jl_datetime) {
        this.jl_datetime = jl_datetime;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

}
