package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "XTCSJG".
 */
public class XTCSJG {

    private Long id;
    private Integer xtcsjg_id;
    private Integer score;
    private Integer number_error;
    private Integer number_success;
    private Integer duration;
    private java.util.Date jg_datetime;
    private String test_group_number;
    private String user_id;
    private String tableName;

    public XTCSJG() {
    }

    public XTCSJG(Long id) {
        this.id = id;
    }

    public XTCSJG(Long id, Integer xtcsjg_id, Integer score, Integer number_error, Integer number_success, Integer duration, java.util.Date jg_datetime, String test_group_number, String user_id, String tableName) {
        this.id = id;
        this.xtcsjg_id = xtcsjg_id;
        this.score = score;
        this.number_error = number_error;
        this.number_success = number_success;
        this.duration = duration;
        this.jg_datetime = jg_datetime;
        this.test_group_number = test_group_number;
        this.user_id = user_id;
        this.tableName = tableName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getXtcsjg_id() {
        return xtcsjg_id;
    }

    public void setXtcsjg_id(Integer xtcsjg_id) {
        this.xtcsjg_id = xtcsjg_id;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getNumber_error() {
        return number_error;
    }

    public void setNumber_error(Integer number_error) {
        this.number_error = number_error;
    }

    public Integer getNumber_success() {
        return number_success;
    }

    public void setNumber_success(Integer number_success) {
        this.number_success = number_success;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public java.util.Date getJg_datetime() {
        return jg_datetime;
    }

    public void setJg_datetime(java.util.Date jg_datetime) {
        this.jg_datetime = jg_datetime;
    }

    public String getTest_group_number() {
        return test_group_number;
    }

    public void setTest_group_number(String test_group_number) {
        this.test_group_number = test_group_number;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

}
