package com.neusoft.sample.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "XTDCTM".
 */
public class XTDCTM {

    private Long id;
    private String xtdctm_id;
    private String examination_number;
    private Integer ismastered;
    private String test_group_number;
    private String user_id;
    private String tableName;

    public XTDCTM() {
    }

    public XTDCTM(Long id) {
        this.id = id;
    }

    public XTDCTM(Long id, String xtdctm_id, String examination_number, Integer ismastered, String test_group_number, String user_id, String tableName) {
        this.id = id;
        this.xtdctm_id = xtdctm_id;
        this.examination_number = examination_number;
        this.ismastered = ismastered;
        this.test_group_number = test_group_number;
        this.user_id = user_id;
        this.tableName = tableName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getXtdctm_id() {
        return xtdctm_id;
    }

    public void setXtdctm_id(String xtdctm_id) {
        this.xtdctm_id = xtdctm_id;
    }

    public String getExamination_number() {
        return examination_number;
    }

    public void setExamination_number(String examination_number) {
        this.examination_number = examination_number;
    }

    public Integer getIsmastered() {
        return ismastered;
    }

    public void setIsmastered(Integer ismastered) {
        this.ismastered = ismastered;
    }

    public String getTest_group_number() {
        return test_group_number;
    }

    public void setTest_group_number(String test_group_number) {
        this.test_group_number = test_group_number;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

}
