package com.neusoft.sample.View.Onetwo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEXT_ONE_STRUCTURE".
 */
public class TextOneStructure implements Comparable<TextOneStructure> {

    private Long id;
    /** Not-null value. */
    private String chapterNo;
    private Integer showSequence;
    private Integer chapterSequence;
    private String chapterSequenceName;
    private String chapterName;
    private String hasSectionNum;
    private Boolean hasResource;
    private Boolean FullFree;

    public TextOneStructure() {
    }

    public TextOneStructure(Long id) {
        this.id = id;
    }

    public TextOneStructure(Long id, String chapterNo, Integer showSequence, Integer chapterSequence, String chapterSequenceName, String chapterName, String hasSectionNum, Boolean hasResource, Boolean FullFree) {
        this.id = id;
        this.chapterNo = chapterNo;
        this.showSequence = showSequence;
        this.chapterSequence = chapterSequence;
        this.chapterSequenceName = chapterSequenceName;
        this.chapterName = chapterName;
        this.hasSectionNum = hasSectionNum;
        this.hasResource = hasResource;
        this.FullFree = FullFree;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getChapterNo() {
        return chapterNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChapterNo(String chapterNo) {
        this.chapterNo = chapterNo;
    }

    public Integer getShowSequence() {
        return showSequence;
    }

    public void setShowSequence(Integer showSequence) {
        this.showSequence = showSequence;
    }

    public Integer getChapterSequence() {
        return chapterSequence;
    }

    public void setChapterSequence(Integer chapterSequence) {
        this.chapterSequence = chapterSequence;
    }

    public String getChapterSequenceName() {
        return chapterSequenceName;
    }

    public void setChapterSequenceName(String chapterSequenceName) {
        this.chapterSequenceName = chapterSequenceName;
    }

    public String getChapterName() {
        return chapterName;
    }

    public void setChapterName(String chapterName) {
        this.chapterName = chapterName;
    }

    public String getHasSectionNum() {
        return hasSectionNum;
    }

    public void setHasSectionNum(String hasSectionNum) {
        this.hasSectionNum = hasSectionNum;
    }

    public Boolean getHasResource() {
        return hasResource;
    }

    public void setHasResource(Boolean hasResource) {
        this.hasResource = hasResource;
    }

    public Boolean getFullFree() {
        return FullFree;
    }

    public void setFullFree(Boolean FullFree) {
        this.FullFree = FullFree;
    }
    @Override
    public int compareTo(TextOneStructure another) {
        if (showSequence.intValue()<another.getShowSequence().intValue())
            return -1;
        else if (showSequence.intValue()==another.getShowSequence().intValue())return 0;

        else return 1;
    }
}
