package com.neusoft.sample.View.Onetwo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEXT_TWO_STRUCTURE".
 */
public class TextTwoStructure implements Comparable<TextTwoStructure> {

    private Long id;
    /** Not-null value. */
    private String sectionNo;
    private Integer showSequence;
    private Integer sectionSequence;
    private String sectionSequenceName;
    private String sectionName;
    private Boolean hasResource;
    private Boolean Free;
    private String chapterNo;
    private String kpNo;

    public TextTwoStructure() {
    }

    public TextTwoStructure(Long id) {
        this.id = id;
    }

    public TextTwoStructure(Long id, String sectionNo, Integer showSequence, Integer sectionSequence, String sectionSequenceName, String sectionName, Boolean hasResource, Boolean Free, String chapterNo, String kpNo) {
        this.id = id;
        this.sectionNo = sectionNo;
        this.showSequence = showSequence;
        this.sectionSequence = sectionSequence;
        this.sectionSequenceName = sectionSequenceName;
        this.sectionName = sectionName;
        this.hasResource = hasResource;
        this.Free = Free;
        this.chapterNo = chapterNo;
        this.kpNo = kpNo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSectionNo() {
        return sectionNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSectionNo(String sectionNo) {
        this.sectionNo = sectionNo;
    }

    public Integer getShowSequence() {
        return showSequence;
    }

    public void setShowSequence(Integer showSequence) {
        this.showSequence = showSequence;
    }

    public Integer getSectionSequence() {
        return sectionSequence;
    }

    public void setSectionSequence(Integer sectionSequence) {
        this.sectionSequence = sectionSequence;
    }

    public String getSectionSequenceName() {
        return sectionSequenceName;
    }

    public void setSectionSequenceName(String sectionSequenceName) {
        this.sectionSequenceName = sectionSequenceName;
    }

    public String getSectionName() {
        return sectionName;
    }

    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    public Boolean getHasResource() {
        return hasResource;
    }

    public void setHasResource(Boolean hasResource) {
        this.hasResource = hasResource;
    }

    public Boolean getFree() {
        return Free;
    }

    public void setFree(Boolean Free) {
        this.Free = Free;
    }

    public String getChapterNo() {
        return chapterNo;
    }

    public void setChapterNo(String chapterNo) {
        this.chapterNo = chapterNo;
    }

    public String getKpNo() {
        return kpNo;
    }

    public void setKpNo(String kpNo) {
        this.kpNo = kpNo;
    }
    @Override
    public int compareTo(TextTwoStructure another) {
        if (showSequence.intValue()<another.showSequence.intValue())return -1;
        else  if (showSequence.intValue()==another.showSequence.intValue())return 0;
        else return 1;
    }

}
